version: '3.8'

services:
  app-postgres:
    container_name: app-postgres
    image: postgres:14.8
    environment:
      POSTGRES_DB: memes
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./app-postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${APP_DB_USERNAME} -d memes" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
