version: '3.8'

services:
  app-postgres:
    container_name: app-postgres
    image: postgres:14.8
    environment:
      POSTGRES_DB: memes
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./app-postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d memes" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]
  app:
    container_name: app
    image: memed-core:latest
    environment:
      MEMES_DB_URL: jdbc:postgresql://app-postgres:5432/memes
      MEMES_DB_USERNAME: admin
      MEMES_DB_PASSWORD: admin
      MEMES_SECURITY_SECRET: A1B2C3D4E5F6A7B8C9D0E1F2A3B4C5D6E7F8A9B0C1D2E3F4A5B6C7D8E9F0
      MEMES_SECURITY_ADMIN_USERNAME: admin
      MEMES_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      app-postgres:
        condition: service_healthy
    volumes:
      - ./logs:/workspace/logs
    restart: always
    ports:
      - "8080:8080"
