version: '3.8'

services:
  app-postgres:
    container_name: app-postgres
    image: postgres:14.8
    environment:
      POSTGRES_DB: memes
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./app-postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d memes" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]
  app:
    container_name: app
    image: yerasylaitkazy/memed-core:latest
    environment:
      DB_URL: jdbc:postgresql://app-postgres:5432/memes
      DB_USERNAME: admin
      DB_PASSWORD: admin
    depends_on:
      app-postgres:
        condition: service_healthy
    restart: always
    ports:
      - "8080:8080"
