spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    web:
      pageable:
        one-indexed-parameters: true

memed:
  security:
    admin-username: ${SECURITY_ADMIN_USERNAME}
    admin-password: ${SECURITY_ADMIN_PASSWORD}
    secret: ${SECURITY_SECRET}
    expiration-in-ms: 600000
  application:
    grade-min: 0
    grade-max: 100

